### PR TITLE
Refactored library

### PR DESCRIPTION
**Pull request by mashhoodr**
@alqamabinsadiq I saw your code and have created this PR just to show how big a difference there can be in writing the same thing in React. The only functionality I have changed is the startDate param which now takes a string rather than a date. I hope I havnt broken any other functionality. Hopefully you will find this helpful.

I have a few more changes in mind if you decide to merge this. :)

### CODE REVIEW

**Comment by alqamabinsadiq** [comment]
@mashhoodr Thank you so much. I was about to convert my code into the same thing but you did it in a better way. Once again thank you so much :)

**Review by alqamabinsadiq — APPROVED** [review]

**Comment by alqamabinsadiq** [comment]
@mashhoodr Did you run the `nom run build` command? I am getting an error while running build script. It's because you changed the `.babelrc`. Let me know if you know anything related to this.

**Comment by mashhoodr** [comment]
@alqamabinsadiq yes I built it and run it locally as well. Did you remove your local node_modules and reinstalled them?

**Comment by alqamabinsadiq** [comment]
@mashhoodr Yes I did that but still I am unable to generate new build.

**Comment by mashhoodr** [comment]
Can you please share the error

**Comment by alqamabinsadiq** [comment]
Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.
It's because of the environment variable. One way to solve this is to use react-scripts but I don't think we need to use react-scripts here. It should work fine as we are doing everything correctly.

**Comment by mashhoodr** [comment]
Try setting NODE_ENV=production in your env, on linux/mac you need can do export NODE_ENV=production

**Comment by alqamabinsadiq** [comment]
For future I am planning to implement circles.

**Comment by alqamabinsadiq** [comment]
@mashhoodr I solved this by adding a new package `dotenv` to my project. It helps in loading environment variables from a .env file.

**Comment by mashhoodr** [comment]
alright that works as well

**Pull request merged**
